### ISSUE TITLE
ClusterServer + body-parser "Error: request size did not match content length"

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#123]
When sending special UTF8 characters on regular HTTP requests, the server is throwing this error after a while.

**Error:**

```
Error: request size did not match content length
    at IncomingMessage.onEnd (/root/crashracing-production/build/node_modules/raw-body/index.js:298:12)
    at emitNone (events.js:86:13)
    at IncomingMessage.emit (events.js:185:7)
    at process.<anonymous> (/root/crashracing-production/build/node_modules/colyseus/lib/cluster/Worker.js:71:21)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/root/crashracing-production/build/node_modules/signal-exit/index.js:155:32)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

How to reproduce:
- Start `ClusterServer`, accepting http requests from the worker.
- Make an http request sending special UTF8 characters.
- Wait a couple of seconds and the error will be thrown

```
 curl -XPOST 'http://localhost:8080/something' -H "Content-Type: application/json"  -d '{"name":"áéíóú"}'
```

This pull-request fixes this problem by re-evaluating the `"content-length"` when forwarding the http request to one of its workers.

**Comment by endel** [comment]
Created this issue by mistake. Sorry.
