### ISSUE TITLE
TypeError: Cannot read property 'removeListener' of undefined

### ISSUE THREAD

**Issue by endel** [gamestdio/colyseus#125]
This error happened on my game today (https://crashracing.com/), using `ClusterServer`.

```
TypeError: Cannot read property 'removeListener' of undefined
    at httpSocketSetup (_http_common.js:219:9)
    at Server.connectionListener (_http_server.js:301:3)
    at emitOne (events.js:96:13)
    at Server.emit (events.js:188:7)
    at process.<anonymous> (/root/crashracing-production/build/node_modules/colyseus/lib/cluster/Worker.js:51:20)
    at emitTwo (events.js:111:20)
    at process.emit (events.js:191:7)
    at processEmit [as emit] (/root/crashracing-production/build/node_modules/signal-exit/index.js:155:32)
    at process.nextTick (internal/child_process.js:744:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback (internal/process/next_tick.js:122:9)
```

After this error happens, the worker crashes and is restarted automatically.

**Comment by endel** [comment]
`ClusterServer` has been deprecated and this issue shouldn't happen anymore (https://github.com/gamestdio/colyseus/pull/135)
