### ISSUE TITLE
Async `onLeave` causes unhandled error when client disconnects

### ISSUE THREAD

**Issue by oyed** [gamestdio/colyseus#171]
When the Client disconnected immediately, such as refreshing the page, and the Server has an async `onLeave`, the following error is triggered:

`WebSocket is not open: readyState 2 (CLOSING)`

Presumably because Colyseus is trying to send the event stating that `onLeave` has finished, but the client is already disconnected.

**Comment by oyed** [comment]
This seems to be the `send` call causing it: https://github.com/gamestdio/colyseus/blob/master/src/MatchMaker.ts#L60

**Comment by endel** [comment]
Thanks for reporting @oyed, I'm having the same issue sometimes and didn't know the cause of it!

**Comment by endel** [comment]
Stack trace reported from @seiyria on [gitter](https://gitter.im/gamestdio/colyseus):

```
Error: WebSocket is not open: readyState 3 (CLOSED)
1
at WebSocket.send (/app/node_modules/ws/lib/websocket.js line 314 col 19)
const err = new Error(
2
at presence.subscribe (/app/node_modules/colyseus/lib/MatchMaker.js line 46 col 32)
client.send(new Buffer(data), { binary: true });
3
at <unknown> (subscriptions.(anonymous function) (/app/node_modules/colyseus/lib/presence/MemsharedPresence.js line 17 col 50)
4
at <unknown> (/app/node_modules/memshared/lib/commands/pubsub.js line 73 col 64)
subscriptions[topic].forEach(function (c) { return c(message); });
5
at Array.forEach (<anonymous> line (unknown))
6
at publish (/app/node_modules/memshared/lib/commands/pubsub.js line 73 col 34)
subscriptions[topic].forEach(function (c) { return c(message); });
7
at process.workerHandleIncomingMessage (/app/node_modules/memshared/lib/index.js line 30 col 31)
commands[message.cmd].apply(undefined, message.args);
8
at process.emit (events.js line 187 col 15)
9
at emit (internal/child_process.js line 811 col 12)
10
at process._tickCallback (internal/process/next_tick.js line 63 col 19)
```

**Comment by seiyria** [comment]
Possibly another error related to this:

```
2018-10-17T18:56:13.687660502Z app[web.1]: TypeError: First argument must be a valid error code number
2018-10-17T18:56:13.687677345Z app[web.1]:     at Sender.close (/app/node_modules/ws/lib/sender.js:112:13)
2018-10-17T18:56:13.687692533Z app[web.1]:     at WebSocket.close (/app/node_modules/ws/lib/websocket.js:207:18)
2018-10-17T18:56:13.687707561Z app[web.1]:     at presence.subscribe (/app/node_modules/colyseus/lib/MatchMaker.js:46:32)
2018-10-17T18:56:13.687723130Z app[web.1]:     at RedisClient.subscriptions.(anonymous function) (/app/node_modules/colyseus/lib/presence/RedisPresence.js:30:17)
2018-10-17T18:56:13.687738328Z app[web.1]:     at RedisClient.emit (events.js:187:15)
2018-10-17T18:56:13.687752865Z app[web.1]:     at return_pub_sub (/app/node_modules/redis/index.js:786:18)
2018-10-17T18:56:13.687768173Z app[web.1]:     at RedisClient.return_reply (/app/node_modules/redis/index.js:833:9)
2018-10-17T18:56:13.687783051Z app[web.1]:     at JavascriptRedisParser.returnReply (/app/node_modules/redis/index.js:192:18)
2018-10-17T18:56:13.687797848Z app[web.1]:     at JavascriptRedisParser.execute (/app/node_modules/redis-parser/lib/parser.js:574:12)
2018-10-17T18:56:13.687813287Z app[web.1]:     at Socket.<anonymous> (/app/node_modules/redis/index.js:274:27)
2018-10-17T18:56:13.687828576Z app[web.1]:     at Socket.emit (events.js:182:13)
2018-10-17T18:56:13.687842922Z app[web.1]:     at addChunk (_stream_readable.js:283:12)
2018-10-17T18:56:13.687857468Z app[web.1]:     at readableAddChunk (_stream_readable.js:264:11)
2018-10-17T18:56:13.687871654Z app[web.1]:     at Socket.Readable.push (_stream_readable.js:219:10)
2018-10-17T18:56:13.687885930Z app[web.1]:     at TCP.onread (net.js:639:20)
```

**Comment by oyed** [comment]
Can't say I've encountered that specific error - maybe worth checking websocket status before sending data in general? @endel

**Comment by endel** [comment]
I'm not sure this is the same problem as @seiyria 
 reported here https://github.com/gamestdio/colyseus/pull/189#issuecomment-433772229, let me know if version [`0.9.18`](https://github.com/gamestdio/colyseus/releases/tag/0.9.18) fixes this for you!

**Comment by oyed** [comment]
Haven't had the issue since, so I'll close this. If it occurs again now that my projects are upgraded, I'll re-open the issue. Thanks @endel!
