### ISSUE TITLE
Matchmaker logs error when client tries to join invalid room

### ISSUE THREAD

**Issue by Alexnortung** [gamestdio/colyseus#197]
## Context

When a client tries to join a room, but the room doesn't exist, the server will log an error

```
Error: Failed to join invalid room "mws2izdX6"
    at MatchMaker.<anonymous> (C:\Users\alex_\Desktop\source\colorify4p\node_modules\colyseus\lib\MatchMaker.js:124:23)
    at Generator.next (<anonymous>)
    at fulfilled (C:\Users\alex_\Desktop\source\colorify4p\node_modules\colyseus\lib\MatchMaker.js:4:58)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
In my case I don't want the console to be flooded with errors if multiple players try to join invalid rooms. 

Solution suggestion:
Instead of throwing an error on the client side and logging an error on the server, it could send some kind of message to the client if it was successful joining or not.

## Your Environment

* Colyseus Version: ^0.9.14
* Node.js Version: 8.9.3
* Operating System and version: Microsoft Windows 10 Home version 1803
* Link to your project: https://bitbucket.org/Nortung/colorify4p/src/master/

**Comment by oyed** [comment]
I agree - it should be an info log, not an error.

**Comment by Alexnortung** [comment]
> I agree - it should be an info log, not an error.

Well yes, but I still think it should be possible to disable the log on the server.
