### ISSUE TITLE
On Windows, file is displayed as playable media file

### ISSUE THREAD

**Issue by WillWammer** [gamestdio/colyseus#199]
I just downloaded the latest Colyseus version, with Node.js with the following command:

`git clone https://github.com/gamestdio/colyseus-examples.git
cd colyseus-examples
npm run bundle-colyseus-client
npm install
npm start
`

In my browser I get a ton of errors for the examples, plus, the files show as playable media files. What's going on here?

**Comment by endel** [comment]
Hi @WillWammer, can you paste the errors you're having here? Cheers

**Comment by WillWammer** [comment]
> Hi @WillWammer, can you paste the errors you're having here? Cheers

@endel 

```
SyntaxError: Unexpected token *
    at new Script (vm.js:79:7)
    at createScript (vm.js:251:10)
    at Object.runInThisContext (vm.js:303:10)
    at Module._compile (internal/modules/cjs/loader.js:656:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:699:10)
    at Module.load (internal/modules/cjs/loader.js:598:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:537:12)
    at Function.Module._load (internal/modules/cjs/loader.js:529:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:741:12)
    at startup (internal/bootstrap/node.js:285:19)
```

Also, where can I find a tutorial of extended docs? I'm not seeing much in the /docs section of the website

**Comment by endel** [comment]
Hi @WillWammer, this error doesn't seem to be related to Colyseus. Can you share your repository where I can reproduce this?
