### ISSUE TITLE
PM2: Problem starting server with 0.5.0-alpha.6

### ISSUE THREAD

**Issue by Tazer** [gamestdio/colyseus#66]
I'm getting the following error, the error is when running in pm2.
I have the following command to start: `pm2 start index.js --node-args='--harmony --harmony-proxies --use-strict`

```
1|index    | /var/www/c-c-c-combo/backend/node_modules/colyseus/lib/matchmaking/Process.js:68
1|index    |                 if (availableWorkerIds.length > 0) {
1|index    |                                       ^
1|index    | TypeError: Cannot read property 'length' of undefined
1|index    |     at Object.21837:1 (/var/www/c-c-c-combo/backend/node_modules/colyseus/lib/matchmaking/Process.js:68:39)
1|index    |     at Store.consume (/var/www/c-c-c-combo/backend/node_modules/memshared/lib/Store.js:25:47)
1|index    |     at process.workerHandleIncomingMessage (/var/www/c-c-c-combo/backend/node_modules/memshared/lib/index.js:31:19)
1|index    |     at emitTwo (events.js:111:20)
1|index    |     at process.emit (events.js:191:7)
1|index    |     at process.nextTick (internal/child_process.js:758:12)
1|index    |     at _combinedTickCallback (internal/process/next_tick.js:73:7)
1|index    |     at process._tickCallback (internal/process/next_tick.js:104:9)
```
My index.js looks like this:

```
import * as cluster from 'cluster';
import chatRoom from './rooms/chat_room';
import gameRoom from './rooms/game_room';
import highscoreRoom from './rooms/highscore_room';


const colyseus = require('colyseus');
const express = require('express');

const port = process.env.PORT || 3553;

const gameServer = new colyseus.ClusterServer();

gameServer.register('chat_room', chatRoom);
gameServer.register('game_room', gameRoom);
gameServer.register('highscore_room', highscoreRoom);
if (cluster.isMaster) {
  gameServer.listen(port);
} else {
  console.log('Worker spawned', process.pid);
  const app = express();
  // app.listen(port);

  // Create HTTP Server
  gameServer.attach({ app });
}
```

**Comment by endel** [comment]
Hey @Tazer, thanks for reporting, but unfortunately there's no support for PM2 at the moment.

There's plans to supporting it though: https://github.com/gamestdio/colyseus/issues/56

Given the current match-making architecture, it would be necessary to manually balance the load and communicate between PM2 processes. Maybe the architecture will need to change to support PM2.

**Comment by Tazer** [comment]
@endel ah! did think that the recently added "cluster" support was for pm2 , I will try to get it work correctly via `forever` instead.
